README.md
bin/chrome-tabs

Chrome sometimes munches all your tabs when it crashes, this script lets
you capture all the urls & tabs you have open in Chrome.
Only works on MacOS since it relies on osascript.

Add @philsnow's tabsaver for Chrome

---

README.md
bin/set-mojave-disk-warning-threshold

Mojave has a pain in the ass warning about not enough disk being free, and on my MBA, it pops up every few minutes. Fuck that noise.
Add `set-mojave-disk-warning-threshold` script that allows you to set the warning threshold to a different number of gigabytes of free space before Mojave whines at you.

Add script to change the Mojave disk space warning threshold

---

bin/unfuck-captive-portal

Sometimes macOS' captive portal detection shits the bed and won't render the html for a wifi captive portal page, so you can't get onto WIFI.
You can work around this by opening Apple's hotspot detection page in Safari, so here's a command line tool to do so.

Cope with WIFI captive portal mishandling by macOS

---

README.md
bin/disable-bouncing-dock-icons
bin/enable-bouncing-dock-icons
bin/macos-menubar-dark
bin/macos-menubar-light

* Add `disable-bouncing-dock-icons` and `enable-bouncing-dock-icons` to tumult
* Update macos-menubar-{dark,light} modes

Add dock bounce controllers

---

README.md
bin/google

Add `google` - uses your default browser to do a google search that you specify from the command line.

Add script to google search from the command line

---

README.md
bin/battery-prompt
bin/get-wifi-password
bin/google
bin/iterm
bin/markdown-open

This plugin already only adds itself to `$PATH` when running on macOS, so I prefer to keep my mac-only scripts in it.
Moved `battery-prompt`, `get-wifi-password`, `iterm` and `markdown-open` scripts from the jpb zsh plugin to here.

Refactor commands out of jpb plugin

---

README.md

zgen is stale and not getting maintained, zgenom is getting updates, use it instead.

zgen is stale, switch to zgenom in readme

---

README.md
bin/pubkey

`pubkey` loads the named (or `id_rsa` by default) key's public part onto your clipboard.
I do this often enough that it got tiresome doing it by hand, so I'm moving the script out of my private scripts and into tumult.

Adds pubkey script

---

README.md
bin/hide-dotfiles
bin/pbclean
bin/pbsort
bin/show-dotfiles
bin/wifi
tumult.plugin.zsh

- Move `pbclean`, `pbsort`, `wifi`, `show-dotfiles` and `hide-dotfiles` functions into scripts to make them usable by non-ZSH shells
- Clean up README.md

Move more functions to scripts

---

README.md
bin/hide-desktop-icons
bin/manp
bin/manpreview
bin/show-desktop-icons
tumult.plugin.zsh

Apple really sucks at keeping command line tooling up to date, either through fear of GPLv3 or plain old indifference.
- Update the logic that finds newer versions to check for brew binaries in `$(brew --prefix)/bin` and not just assume it will install to `/usr/local/bin`
- Add `manpreview` script
- Convert `hide-desktop-icons` and `show-desktop-icons` to scripts so non-ZSH users can use them.
- `mywireless` alias was broken by macOS updates, make it an alias to `wifi-name` which works

Improve override of stale macOS binaries

---

tumult.plugin.zsh

The missing space between the closing quote and the closing square brackets was causing a syntax error on zsh v5.8/ubuntu.
-- There was no credits section and I don't require credit for a simple typo fix like this, but will force-push the addition if you want.

Add space before close of brew section's tests

---

README.md
bin/charger-wattage

Add `charger-wattage` - this will help detect when your USB-C cable is not rating for enough wattage for your power brick, or that your monitor is not providing enough juice.
Both of those can lead to your laptop slowly draining while plugged in.

Add charger-wattage script

---

tumult.plugin.zsh

Had `'` characters where there should have been `"`, which made the vim alias include the text `${BREW_PREFIX}` instead of correctly interpolating the value.
Fixes #94

Fix vim alias setting

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
bin/lockscreen
bin/start-screensaver
tumult.plugin.zsh

- `ScreenSaverEngine.app` is moved in Monterey, cope while remaining compatible with old macOS versions
- Add fallback to `osascript` if we can't find `ScreenSaverEngine.app`.  It's more brittle, but at least it's something.
- Add `start-screensaver` alias
- Note in readme that `lockscreen` only locks if System Preferences are set to lock after screen saver starts.
- Yank `Sublime Text` alias setting, leave that to end user preferences

Update lockscreen for Monterey

---

.github/PULL_REQUEST_TEMPLATE.md
bin/battery-percentage
bin/battery-time

Per `shellcheck`, replace `egrep` with `grep -E`.

Replace egrep with grep -E

---

README.md
bin/power-source

Add `power-source` script. It can be used by other scripts to detect whether a laptop is running on battery or not. Includes a `--emoji` option so it can easily be used in prompts.

Add `power-source` script

---

README.md

Fix typo in Oh-My-ZSH install instructions

Fix typo in Oh-My-ZSH install instructions

---

README.md
bin/pbclean
bin/pbclean-ansi
bin/pbindent
bin/pbsed
bin/pbsort

Add `pbclean-ansi` helper script to remove ANSI color codes from the clipboard.

Add `pbclean-ansi`

---

tumult.plugin.zsh

- As installed by `brew`, `groovy`, `go` and `npm` all need more directories added to the user's `$PATH` to work as expected.
- Cope with macOS non-standard way of updating locate db by adding aliases to simplify updating the locate db on macOS

Add helpers for `updatedb`, extend `PATH` for `groovy`, `go` and `npm`

---

tumult.plugin.zsh

Stop stepping on `$EDITOR` and `$VISUAL` if the user has them set.

Respect user `$EDITOR` and `$VISUAL` when present

---

.github/workflows/awesomebot.yml
.github/workflows/mega-linter.yml
bin/screencap-stream

- Switch to option handling with `getopt`
- Store frames in `$SCRATCH_D` so we clean up after ourselves
- Add `-k` option to keep the captured frames after rendering a movie

Improve `screencap-stream`

---

README.md

Add [complete-mac](https://github.com/vitkabele/complete-mac) ZSH tab completions for `ioreg`, `lsmp`, `scselect`, `system_profiler` and `tmutil` commands.

Add `complete-mac`

---

README.md
bin/dns-resolvers

I can never remember the right `scutil` command to show the resolvers macOS is using, so add a helper to print them.

Add `dns-resolvers` script

---

.github/workflows/pre-commit.yml
Contributing.md

Add missing blank line before H2 heading in Contributing.md

Humor markdownlint in Contributing.md

---

.github/workflows/awesomebot.yml
README.md
bin/spotlight-reindex
tumult.plugin.zsh

- Check links in README.md daily
- Add `spotlight-reindex` script
- Update copyright

Add spotlight index rebuild command
