- tumult.plugin.zsh
* Stop stepping on ls aliases - Closes #1
* Add open_dot alias to render a dot file and view in Preview.app
* Add flushds alias
> Alias cleanup

- tumult.plugin.zsh
`reveal /path/to/file` will open the enclosing directory in a Finder
window
> Add reveal alias

- README.md
- bin/imgcat
Display an image directly in your terminal. Only works with iTerm 2
> Add imgcat

- README.md
- bin/720p
- bin/battery-percentage
- bin/disable-startup-chime
- bin/eject-all
- bin/enable-startup-chime
- bin/evernote
- bin/get-iterm2-buffer
- bin/kill-screensaver
- bin/pledit
- bin/unquarantine
- tumult.plugin.zsh
* Move pledit to a real script so the non-zsh users can still use it
* Move unquarantine to a separate script
* Update mysql and postgresql loader helpers
* Move kill-screensaver into separate script
* Add macOS checks to scripts that needed them
* Cleanup doc comments
> Refactor plugin file

- README.md
- bin/get-wallpaper-path
- setup.py
diceware-password generates a random but memorable passphrase using the Diceware Passphrase Algorithm. See [http://world.std.com/~reinhold/diceware.html](http://world.std.com/~reinhold/diceware.html)
> Add diceware-password

- bin/macos-menubar-dark
- bin/macos-menubar-light
Make it clear the menubar commands are mac-only
> Add symlinks to menubar commands

- LICENSE
- README.md
* LICENSE was missing my name
* Add Apache License badge to README.md
* Minor wording tweaks and link updates
> Tweak readme and License

- README.md
- tumult.plugin.zsh
* Add link to [apple-touchbar](https://github.com/zsh-users/zsh-apple-touchbar)
* Add link to [sekey](https://github.com/ntrippar/sekey)
* Sort **Other Useful macOS tools** section
> Add links to sekey and apple-touchbar

- README.md
- bin/focusmode-disable
- bin/focusmode-enable
They're macOs-specific, they belong here.
Add scripts to enable and disable single-app mode
> Move focus scripts from jpb.zshplugin

- bin/macos-menubar-dark
- bin/macos-menubar-light
Fix permissions on macos-menubar-*
> Fix permissions on macos-menubar-*

- README.md
> Clean up external resources section

- PULL_REQUEST_TEMPLATE.md
- README.md
> Update PR template

- README.md
Forgot to commit the documentation
> Document bin/unfuck-captive-portal

- .circleci/config.yml
- .travis.yml
- README.md
> Switch to circleci from travis

- README.md
* Minor wording tweaks in README.md
> Minor wording tweaks in README.md

- README.md
* Minor wording tweaks
* Explain how `unfuck-captive-portal` works
> Explain how unfuck-captive-portal works

- README.md
- bin/disable-network-ds-store
- bin/enable-network-ds-store
Add enable/disable-network-ds-store scripts
> Add enable/disable-network-ds-store

- bin/focusmode-disable
- bin/focusmode-enable
The original focusmode-disable actually enables focus mode, while the focusmode-enable disables focus mode
> inverse focusmode-disable/enable

- README.md
- bin/keychainctl
* Add keychainctl script - CRUD operations on keychains
> Add keychainctl script

- bin/macos-major-version
- bin/osx-major-version
- bin/zap-ds-store
- tumult.plugin.zsh
Refactor some functions and aliases to scripts to make it easier for non-ZSH users to use this collection.
> Start refactoring functions/aliases to scripts 

- bin/mergepdfs
- tumult.plugin.zsh
> refactor out mergepdfs

- README.md
- tumult.plugin.zsh
Add `quicklook` command to trigger quicklook previews for files
> Add quicklook command

- bin/quicklook
> Add quicklook script

- README.md
- bin/macos-alert
- bin/macos-notification
- Add `macos-alert` that displays an alert on macOs
- Add `macos-notification` that displays a notification with the macOs notification manager
> Add macOs alert and notification scripts

- bin/macos-notification
Forgot to commit the sound option to `macos-notification`.
> Add sound option to macos-notification

- README.md
- bin/kill-sophos-dead
Add `kill-sophos-dead` script to kill Sophos' useless scanner process so you can get actual work done.
> Add kill-sophos-dead script

- README.md
- bin/kill-sophos-dead
- bin/time-machine-log-viewer
Add time-machine-log-viewer script
> Add time-machine-log-viewer script

- bin/time-machine-log-viewer
I prefer to see a stream of events as they come in.
> Use log stream instead of log show

- .github/workflows/superlinter.yml
- README.md
- bin/clean-file-context-menu
- Add `superlinter` workflow so scripts get shellchecked.
- Add `clean-file-context-menu` script
> Add clean-file-context-menu script, Add superlinter

- README.md
- bin/time-machine-throttle
- bin/time-machine-unthrottle
- bin/timemachine-log-viewer
- bin/timemachine-throttle
- bin/timemachine-unthrottle
Add `time-machine-throttle` and `time-machine-unthrottle` commands.
I'm having issues with extremely slow time machine backups to a smb server, and supposedly disabling throttling will improve performance.
> Add time-machine-throttle and time-machine-unthrottle commands

- .github/workflows/awesomebot.yml
- README.md
> Missed a zgen reference.

- README.md
- Clean up markdown linter complaints about list formatting
- Update license statement
> Clean up markdown linter complaints

- Contributing.md
Update the contributing guidelines to clarify why I want contributions to have licenses, and why standalone scripts are preferred over adding functions and aliases to `tumult.plugin.zsh`.
> Update the contributing guidelines

- README.md
> Fix TOC - replace zgen with zgenom

- bin/mac-alert
- bin/mac-notification
- Added missing symlinks for `mac-alert` and `mac-notification`
> Add missing command symlinks

- .github/workflows/superlinter.yml
Update superlinter configuration to use @v4
> Update superlinter configuration to use @v4

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/superlinter.yml
Renamed the default branch to main, update superlinter accordingly.
- Renamed the default branch to main, update superlinter accordingly.
- Minor tweaks to PR template
> Update superlinter config to use main branch

- README.md
Fix status badge to use main branch
> Fix status badge to use main branch

- README.md
- bin/set-cursor-size
Add `set-cursor-size` based on https://github.com/wookayin/dotfiles/blob/master/bin/cursor-size
> Add `set-cursor-size` script

- bin/lockscreen
> Fix missing `!` in lockscreen

- bin/chrome-tabs
- bin/clip
- bin/fix-airplay
- bin/mkdmg
- bin/mkicns
- bin/pbcurl
- bin/pbindent
- bin/pbsed
- bin/randomize-mac-address
- bin/toggle-ssh
- chrome-tabs
- clip
- mkdmg
- mkicns
- pbindent
- pbsed
> Shellcheck cleanups

- README.md
- bin/screencap-stream
Add `screencap-stream` helper script. Closes #4.
> Add `screencap-stream` script

- tumult.plugin.zsh
quick fix to annoying bug. 
fixes #111
> Fix parse error for local has() function

- .github/workflows/mega-linter.yml
Update mega-linter action to v6
> Update mega-linter action to v6

- README.md
- bin/hide-file
- bin/unhide-file
Add `hide-file` and `unhide-file` helper scripts
> Add `hide-file` and `unhide-file` helper scripts

- README.md
- bin/dump-entitlements
Add `dump-entitlements` from https://github.com/0xmachos/macos-scripts
> Add `dump-entitlements`

- README.md
- bin/bundle-id
> Add `bundle-id`

- .github/workflows/mega-linter.yml
- README.md
- bin/darktoggle
- bin/interface-style
Add `darktoggle` and `interface-style` scripts
> Add `darktoggle` and `interface-style`

- .github/dependabot.yml
- .gitignore
- .mega-linter.yml
- .trivyignore
- Add a config file for mega-linter
- Add `.github/dependabot.yml`
- Add `.trivyignore`
- Update `.gitignore`
> Update linter configuration files

- .github/workflows/pre-commit.yml
Fix yamllint complaint in pre-commit.yml
> Fix yamllint complaint in pre-commit.yml

- tumult.plugin.zsh
Use cleaner path manipulation to add bin dir to `$PATH`
> Use cleaner path manipulation to add bin dir to `$PATH`

- .github/workflows/awesomebot.yml
git.herrbischoff.com has too many timeouts during CI. Have awesomebot ignore it.
> Ignore git.herrbischoff.com

- README.md
- bin/make-ramdisk
Add `make-ramdisk` for when you really need I/O
> Add `make-ramdisk`
